name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn package

    - name: Run tests
      id: run-tests
      continue-on-error: true
      run: mvn test

    - name: Create issue on test failure
      if: steps.run-tests.outcome == 'failure'
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'create-issue'
        title: 'Test failure in build ${{ github.run_number }}'
        body: |
          The tests failed in build ${{ github.run_number }}.
          - Commit: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          - Workflow run: [Link](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          Please check the logs for more details.
        labels: 'bug,test-failure'
        assignees: 'your-github-username'    
